### PR TITLE
New Command /hangman

### PR DESCRIPTION
**Pull request by ArPiiX**

### CODE REVIEW

**Comment by SFFan123** [comment]
Please add:
Callback on invalid command
/hangman help

Please verify:
guess is case insensitive but solve is not, is this intended?

**Comment by ArPiiX** [comment]
Please explain
"Callback on invalid command
/hangman help" further @SFFan123

**Comment by SFFan123** [comment]
if I type a invalid command, nothing happens ... no error or else ...
/hangman help is not there...

**Comment by ArPiiX** [comment]
/hangman help is named info in this case.

**Pull request merged**
